<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="SafetyPLC" Id="{d72391e9-50f0-4b14-82db-156d9d838551}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SafetyPLC
VAR

(*=========================		SAFETY PLC		==========================*)	



(*========================================================================*)

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*=========================		SAFETY PLC		==========================*)



(*========================================================================*) ]]></ST>
    </Implementation>
    <LineIds Name="SafetyPLC">
      <LineId Id="13" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="14" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>